[Settings]
DefaultLayer=default
DebugTooltips=1

[OBS]
Host=127.0.0.1
Port=4455
Password=

[Bindings]

; These are sample bindings only.
; Your actual keyboard number depends on the number assigned in MultiKB.
; Press an unmapped key or use capture mode to copy the correct binding line.

; Example:
; default|1_112=run|notepad.exe
; default|1_113=run|calc.exe
; default|1_114=send|^c
; default|1_115=send|^v
; default|1_116=msg|Hello from keyboard 1 F5
; default|1_117=layer|media
; default|1_118=folder|C:/
; default|1_119=website|https://www.google.com
; default|1_120=editbindings|
; default|1_121=capture|
; default|1_122=capture|

; Example media layer:
; media|1_112=media|playpause
; media|1_113=media|next
; media|1_114=media|prev
; media|1_115=media|mute
; media|1_116=media|volup
; media|1_117=media|voldown
; media|1_118=layer|default

default|1_52=capture
default|1_49=obs_scene|Starting
default|1_50=obs_scene|BRB
default|1_51=obs_scene|Ending
default|1_56=obs_scene|MainCam
default|1_55=obs_scene|MainDesktop_Cam
default|1_76=run|discord.exe
default|1_77=run|"E:\Program Files\obs-studio\bin\64bit\obs64.exe" --use-fake-ui-for-media-stream
default|1_72=run|C:\Users\Arrogant Pixel\AppData\Local\Programs\Microsoft VS Code\Code.exe

default|1_75=run|chrome.exe
default|1_78=run|E:\Unity\6000.2.0f1\Editor\Unity.exe
default|1_71=run|E:\JetBrains\JetBrains Rider 2024.1\bin\rider64.exe
default|1_74=run|notepad.exe
