# Build script for IpinziMacroKeyboard
# Automatically generates #Include statements for compile-time plugins and compiles to EXE

param(
    [string]$ScriptDir = $PSScriptRoot,
    [string]$MainFile = "$ScriptDir\main.ahk",
    [string]$PluginsDir = "$ScriptDir\plugins",
    [switch]$NoCompile = $false,
    [string]$Version = "",
    [string]$OutputExe = "",
    [string]$PluginIgnoreFile = "$ScriptDir\build.plugins.ignore"
)

Write-Host "Building IpinziMacroKeyboard..." -ForegroundColor Cyan

# Verify directories exist
if (-not (Test-Path $MainFile)) {
    Write-Host "ERROR: main.ahk not found at $MainFile" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path $PluginsDir)) {
    Write-Host "ERROR: plugins directory not found at $PluginsDir" -ForegroundColor Red
    exit 1
}

# Require version to be passed in (enforced so users run build.cmd)
if ([string]::IsNullOrWhiteSpace($Version)) {
    Write-Host "ERROR: Version not provided. Please run build.cmd to build." -ForegroundColor Red
    exit 1
}

$BuildRoot = Join-Path $ScriptDir "builds"
$BuildDir = Join-Path $BuildRoot $Version

# Create build folder
if (-not (Test-Path $BuildDir)) {
    New-Item -Path $BuildDir -ItemType Directory -Force | Out-Null
}

# Copy runtime assets
$bindingsFile = Join-Path $ScriptDir "bindings.ini"
if (Test-Path $bindingsFile) {
    Copy-Item -Path $bindingsFile -Destination $BuildDir -Force
}

$dataDir = Join-Path $ScriptDir "data"
if (Test-Path $dataDir) {
    $destData = Join-Path $BuildDir "data"
    if (Test-Path $destData) { Remove-Item -Recurse -Force $destData }
    Copy-Item -Path $dataDir -Destination $BuildDir -Recurse -Force
}

# Target output EXE in build folder
if ([string]::IsNullOrWhiteSpace($OutputExe)) {
    $OutputExe = Join-Path $BuildDir "Ipinzi Macro Keyboard.exe"
}

Write-Host "Build output folder: $BuildDir" -ForegroundColor Cyan
Write-Host "Output EXE: $OutputExe" -ForegroundColor Cyan

# Load optional local plugin ignore list.
$ignoredPlugins = @{}
if (Test-Path $PluginIgnoreFile) {
    Write-Host "Using plugin ignore file: $PluginIgnoreFile" -ForegroundColor Cyan

    foreach ($rawLine in Get-Content -Path $PluginIgnoreFile) {
        $line = $rawLine.Trim()
        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }

        if ($line.StartsWith("#") -or $line.StartsWith(";")) {
            continue
        }

        $ignoredPlugins[$line.ToLowerInvariant()] = $true
    }
}

# Find all compile-time plugin files (those with Action_ functions)
$pluginFiles = @()
$ahkFiles = Get-ChildItem -Path $PluginsDir -Filter "*.ahk" -ErrorAction SilentlyContinue

foreach ($file in $ahkFiles) {
    $content = Get-Content -Path $file.FullName -Raw
    $relativePath = "plugins\$($file.Name)"
    $ignoredByName = $ignoredPlugins.ContainsKey($file.Name.ToLowerInvariant())
    $ignoredByPath = $ignoredPlugins.ContainsKey($relativePath.ToLowerInvariant())
    
    # Check if file contains Action_ functions (compile-time plugin indicator)
    if ($content -match 'Action_\w+\s*\(') {
        if ($ignoredByName -or $ignoredByPath) {
            Write-Host "  [-] Ignored compile-time plugin: $($file.Name)" -ForegroundColor Yellow
            continue
        }

        $pluginFiles += $file.Name
        Write-Host "  [+] Found compile-time plugin: $($file.Name)" -ForegroundColor Green
    } else {
        Write-Host "  [ ] Runtime plugin (skipped): $($file.Name)" -ForegroundColor Gray
    }
}

# Read main.ahk
$mainContent = Get-Content -Path $MainFile -Raw

# Find the marker section for auto-generated includes
$markerStart = ";;; AUTO-GENERATED PLUGIN INCLUDES START"
$markerEnd = ";;; AUTO-GENERATED PLUGIN INCLUDES END"

# Generate include statements
$includeStatements = @(
    "",
    "$markerStart",
    "; The following compile-time plugins are auto-generated by build.ps1"
)

foreach ($plugin in $pluginFiles | Sort-Object) {
    $includeStatements += "#Include plugins\$plugin"
}

$includeStatements += $markerEnd
$includeBlock = $includeStatements -join "`n"

# Check if markers exist
if ($mainContent -match [regex]::Escape($markerStart)) {
    # Replace existing auto-generated block
    $pattern = [regex]::Escape($markerStart) + ".*?" + [regex]::Escape($markerEnd)
    $mainContent = [regex]::Replace($mainContent, $pattern, $includeBlock, [System.Text.RegularExpressions.RegexOptions]::Singleline)
    Write-Host "  [*] Updated existing include block" -ForegroundColor Yellow
} else {
    # Insert before main code (after other #Include statements)
    $insertPoint = $mainContent.LastIndexOf("#Include lib\")
    if ($insertPoint -eq -1) {
        Write-Host "ERROR: Could not find insertion point in main.ahk" -ForegroundColor Red
        exit 1
    }
    
    # Find the end of the line
    $insertPoint = $mainContent.IndexOf("`n", $insertPoint) + 1
    $mainContent = $mainContent.Insert($insertPoint, $includeBlock + "`n")
    Write-Host "  [*] Inserted auto-generated include block" -ForegroundColor Yellow
}

# Write the updated main.ahk
Set-Content -Path $MainFile -Value $mainContent -Encoding UTF8
Write-Host "  [>] Updated: $MainFile" -ForegroundColor Green

# Summary of includes
Write-Host ""
Write-Host "Compile-time plugins:" -ForegroundColor Cyan
if ($pluginFiles.Count -gt 0) {
    $pluginFiles | Sort-Object | ForEach-Object { Write-Host "  [+] $_" }
} else {
    Write-Host "  (none)" -ForegroundColor Gray
}

# Compilation step
if ($NoCompile) {
    Write-Host ""
    Write-Host "Skipped compilation (use -NoCompile `$false to enable)" -ForegroundColor Yellow
    exit 0
}

Write-Host ""
Write-Host "Compiling to EXE..." -ForegroundColor Cyan

# Find AutoHotkey v2 compiler
$ahk2exePath = $null

# Check common installation paths
$possiblePaths = @(
    "C:\Program Files\AutoHotkey\Compiler\ahk2exe.exe",
    "C:\Program Files (x86)\AutoHotkey\Compiler\ahk2exe.exe",
    "${env:PROGRAMFILES}\AutoHotkey\Compiler\ahk2exe.exe",
    "${env:PROGRAMFILES(x86)}\AutoHotkey\Compiler\ahk2exe.exe"
)

foreach ($path in $possiblePaths) {
    if (Test-Path $path) {
        $ahk2exePath = $path
        break
    }
}

# If not found in standard paths, try to find it via registry or environment
if (-not $ahk2exePath) {
    try {
        $ahkReg = Get-ItemProperty -Path "HKLM:\SOFTWARE\AutoHotkey" -ErrorAction SilentlyContinue
        if ($ahkReg.InstallDir) {
            $testPath = Join-Path $ahkReg.InstallDir "v2\Compiler\ahk2exe.exe"
            if (Test-Path $testPath) {
                $ahk2exePath = $testPath
            }
        }
    }
    catch {
        # Registry lookup failed, continue to next check
    }
}

if (-not $ahk2exePath) {
    Write-Host "WARNING: ahk2exe.exe not found" -ForegroundColor Yellow
    Write-Host "  Tried paths:" -ForegroundColor Yellow
    $possiblePaths | ForEach-Object { Write-Host "    $_" -ForegroundColor Gray }
    Write-Host ""
    Write-Host "Please ensure AutoHotkey v2.0 is installed or set PATH environment variable." -ForegroundColor Yellow
    exit 1
}

Write-Host "  Found compiler: $ahk2exePath" -ForegroundColor Gray

# Compile
try {
    # Look for icon file in root directory
    $iconFile = Get-ChildItem -Path $ScriptDir -Filter "*.ico" -ErrorAction SilentlyContinue | Select-Object -First 1
    
    if ($iconFile) {
        Write-Host "  Found icon: $($iconFile.Name)" -ForegroundColor Gray
    }
    
    $compileCmd = @(
        "`"$ahk2exePath`"",
        "/in `"$MainFile`"",
        "/out `"$OutputExe`""
    )
    
    if ($iconFile) {
        $compileCmd += "/icon `"$($iconFile.FullName)`""
    }
    
    Write-Host "  Running: & $($compileCmd -join ' ')" -ForegroundColor Gray

    # Direct invocation is more reliable for ahk2exe in this environment.
    & $ahk2exePath /in "$MainFile" /out "$OutputExe" $(if ($iconFile) { "/icon"; $iconFile.FullName })
    $compileExitCode = $LASTEXITCODE

    # Give the filesystem a moment in case the output appears slightly after process exit.
    $outputExists = $false
    for ($i = 0; $i -lt 10; $i++) {
        if (Test-Path $OutputExe) {
            $outputExists = $true
            break
        }
        Start-Sleep -Milliseconds 200
    }

    if ($outputExists) {
        if ($compileExitCode -ne 0) {
            Write-Host "  [*] Compiler exit code was $compileExitCode but output EXE exists; treating build as successful." -ForegroundColor Yellow
        }

        Write-Host "  [+] Compilation successful!" -ForegroundColor Green
        $fileSize = (Get-Item $OutputExe).Length / 1MB
        Write-Host "  [>] Output: $OutputExe ($([Math]::Round($fileSize, 2)) MB)" -ForegroundColor Green
    } else {
        if ($null -eq $compileExitCode) {
            Write-Host "  [-] Compilation failed (no output EXE produced; compiler exit code unavailable)." -ForegroundColor Red
            exit 1
        }

        Write-Host "  [-] Compilation failed with exit code $compileExitCode" -ForegroundColor Red
        exit $compileExitCode
    }
}
catch {
    Write-Host "  [-] Error during compilation: $_" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Build complete!" -ForegroundColor Green
